---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: awx
  namespace: dev-namespace
spec:
  chart:
    spec:
      chart: awx-operator
      version: "2.5.2"
      sourceRef:
        kind: HelmRepository
        name: awx-operator # Change it if needed
        namespace: flux-system #Change it if needed     
  values:
    AWX:
      enabled: true
      name: awx-dev
      spec:
        service_type: NodePort
        admin_user: admin
        nodeport_port: 30099              
    postgres:
      enabled: true
      host: database-1-instance-1.cqdguar2ilnu.ap-south-1.rds.amazonaws.com
      port: 5432
      dbName: postgres
      username: postgres
      password: Z22gsjG2eTxy