---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: awx
  namespace: dev-namespace
spec:
  chart:
    spec:
      sourceRef:
        namespace: dev-namespace #Change it if needed     
  values:
    AWX:
      enabled: true
      name: awx-dev
      spec:
        nodeport_port: 30099              
      postgres:
        enabled: true
        host: database-1-instance-1.cqdguar2ilnu.ap-south-1.rds.amazonaws.com
        password: Z22gsjG2eTxy