---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: awx
  namespace: 
spec:
  chart:
    spec:
      chart: awx-operator
      version: "2.5.2"
      sourceRef:
        kind: HelmRepository
        name: awx-operator  #Change it if needed
        namespace:  #Change it if needed 
  interval: 10m
  install: 
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1   
  values:
    AWX:
      enabled: true
      name: awx-demo
      spec:
        service_type: NodePort
        admin_user: admin
        nodeport_port: 

      postgres:
        enabled: true
        host: 
        port: 5432
        dbName: postgres
        username: postgres
        password: 


